# Setup
title:               Andrew Hunt
tagline:             ''
description:         'My blog, portfolio, and resume site.'
url:                 https://andrewrhunt.me
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andrew Hunt
  url:               https://twitter.com/andrew_r_hunt
  email:             hunt.andrew.r@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
